server.port=8101
spring.main.banner-mode=off
logging.level.root=WARN
logging.level.org.springframework=WARN
logging.level.org.apache=WARN
spring.threads.virtual.enabled=true
server.tomcat.max-http-form-post-size=1048576
server.tomcat.max-swallow-size=1048576
